### ISSUE TITLE
Image upload problem

### ISSUE THREAD

**Issue by chadlieberman** [wombats-writing-code/fbw-components#6]
I just tried to upload an image and send it to the server, and I got the error message: "Something went wrong. Contact your administrator."

![screenshot from 2016-05-26 13 10 38](https://cloud.githubusercontent.com/assets/1149890/15583373/7e498a96-2343-11e6-9eb2-8d7705a63520.png)

**Comment by coleshaw** [comment]
Sorry, this was a result of using a method not supported in Python 2.6 to add the timestamp onto file uploads. Hopefully we will not see errors like this once we move to the new server in June (because the image upload works on all the other servers…which run Python 2.7). Just deployed a fix, please try it again.

**Comment by chadlieberman** [comment]
Works.
