### ISSUE TITLE
No results found when linking learning outcomes

### ISSUE THREAD

**Issue by chadlieberman** [wombats-writing-code/fbw-components#8]
I don't seem to be able to link learning outcomes to questions or responses in production. The dropdown seems to always indicate "No results found". 

Is there a particular subject or module in which I need to link the outcome for it to become available in the authoring tool for MAT 1 : College Algebra?

**Comment by coleshaw** [comment]
Ah, funny, I just sent Luwen a Skype about this, because I wasn’t sure if we ever included you / Dipa in the conversations around production LOs. Basically we have an individual LO bank set up for each of the domains (CAD, Math, Accounting), separate from what is driving the xoces.mit.edu visualization (that data was scraped from the CCCS system website), so there is no data leakage. So you will have to create your LOs in the Xoces authoring tool, under “FBW_ALGEBRA”.

I just enabled the three banks for you, please try and let me know if you run into any issues.

**Comment by coleshaw** [comment]
Taking a peek at what you’ve done to Math, I will suggest a minor change...Sorry, I should have been more specific when I replied earlier…

The idea is that you still need a two-level hierarchy when you do your outcomes (modules -> outcomes). You will then link the questions to outcomes, and the module is inferred. The Item Authoring app categorizes all questions by module into folders, to make it easier to search (see CAD as an example, and note that the question LOs don’t match the “folders” by name). 

It appears in MAT that you have a 1 level hierarchy (the folder / module names match exactly with the outcome names). I believe that is not the expected FbW structure…each module should have at least a couple outcomes...

**Comment by luwen-huang** [comment]
Was the two level hierarchy enabled for College Algebra too? I thought
Backstage only did that for CAD. In any case, I think having modules is
a good idea regardless.

**Comment by coleshaw** [comment]
I think we talked about doing it for all three domains … or at least, I recall you saying something like “I think we’ll do it for all of them”, so I just went ahead and implemented it for all three, up front, so I wouldn’t have to go back and do it again.

**Comment by luwen-huang** [comment]
Oh, that was not what I was referring to (was meaning the segregation), but
in any case, this works.
